### PR TITLE
Fix positioning bug when point value is zero

### LINKED ISSUE #30138: [Bug]: Test suite crash TypeError: element.getBoundingClientRect is not a function
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 15.22 GB / 30.98 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
```

### Are you reporting Accessibility issue?

None

### Reproduction

comming soon

## Actual Behavior
Tests accessing the Callout are crashing with `TypeError: element.getBoundingClientRect is not a function`

## Expected Behavior
Test suite runs without issues. This is works with 8.112.9.

### Logs

```shell
FAIL  src/jobs/components/__tests__/Jobs.tsx > 
TypeError: element.getBoundingClientRect is not a function
 ❯ _getRectangleFromElement node_modules/@fluentui/react/lib/utilities/src/utilities/positioning/positioning.ts:791:2
 ❯ _getRectangleFromTarget node_modules/@fluentui/react/lib/utilities/src/utilities/positioning/positioning.ts:1011:14
 ❯ Module.getRectangleFromTarget node_modules/@fluentui/react/lib/utilities/positioning/positioning.js:803:12
 ❯ useMaxHeight node_modules/@fluentui/react/lib/components/src/components/Callout/CalloutContent.base.tsx:148:6
 ❯ node_modules/@fluentui/react/lib/components/src/components/Callout/CalloutContent.base.tsx:532:18
 ❯ renderWithHooks node_modules/react-dom/cjs/react-dom.development.js:14985:18
 ❯ updateForwardRef node_modules/react-dom/cjs/react-dom.development.js:17044:20
 ❯ beginWork node_modules/react-dom/cjs/react-dom.development.js:19098:16
 ❯ HTMLUnknownElement.callCallback node_modules/react-dom/cjs/react-dom.development.js:3945:14
 ❯ HTMLUnknownElement.callTheUserObjectsOperation node_modules/jsdom/lib/jsdom/living/generated/EventListener.js
```

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by micahgodbolt**
a reminder to always use ?? when one of the values could be zero

fixes #30138

### CODE REVIEW

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/6338761c14181382764aded29ec99f794a5d8c22'>6338761c14181382764aded29ec99f794a5d8c22</a></sub>
<div id="bundleSizeComment9423"/>

**Review by spmonahan — APPROVED** [review]

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/BaseButton-mount_base.html">609</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/BaseButton-mount.html">632</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Breadcrumb-mount_base.html">1670</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Breadcrumb-mount.html">1674</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Checkbox-mount_base.html">1701</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Checkbox-mount.html">1698</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/CheckboxBase-mount_base.html">1467</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/CheckboxBase-mount.html">1486</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/ChoiceGroup-mount_base.html">2993</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/ChoiceGroup-mount.html">2947</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/ComboBox-mount_base.html">675</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/ComboBox-mount.html">687</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/CommandBar-mount_base.html">6275</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/CommandBar-mount.html">6397</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/ContextualMenu-mount_base.html">12547</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/ContextualMenu-mount.html">12395</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/DefaultButton-mount_base.html">746</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/DefaultButton-mount.html">762</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/DetailsRow-mount_base.html">2157</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/DetailsRow-mount.html">2206</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/DetailsRowFast-mount_base.html">2202</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/DetailsRowFast-mount.html">2153</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/DetailsRowNoStyles-mount_base.html">2000</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/DetailsRowNoStyles-mount.html">2005</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Dialog-mount_base.html">2707</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Dialog-mount.html">2685</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/DocumentCardTitle-mount_base.html">232</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/DocumentCardTitle-mount.html">226</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Dropdown-mount_base.html">1992</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Dropdown-mount.html">1980</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/FocusTrapZone-mount_base.html">1129</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/FocusTrapZone-mount.html">1136</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/FocusZone-mount_base.html">1063</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/FocusZone-mount.html">1087</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/GroupedList-mount_base.html">41687</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/GroupedList-mount.html">41767</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/GroupedList-virtual-rerender_base.html">20064</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/GroupedList-virtual-rerender.html">20151</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">53239</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/GroupedList-virtual-rerender-with-unmount.html">53014</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/GroupedListV2-mount_base.html">217</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/GroupedListV2-mount.html">227</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/GroupedListV2-virtual-rerender_base.html">213</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/GroupedListV2-virtual-rerender.html">216</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">225</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">223</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/IconButton-mount_base.html">1106</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/IconButton-mount.html">1088</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Label-mount_base.html">338</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Label-mount.html">346</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Layer-mount_base.html">2739</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Layer-mount.html">2764</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Link-mount_base.html">400</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Link-mount.html">395</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/MenuButton-mount_base.html">932</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/MenuButton-mount.html">941</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/MessageBar-mount_base.html">21528</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/MessageBar-mount.html">21457</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Nav-mount_base.html">1967</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Nav-mount.html">1988</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/OverflowSet-mount_base.html">787</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/OverflowSet-mount.html">788</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Panel-mount_base.html">2099</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Panel-mount.html">1822</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Persona-mount_base.html">746</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Persona-mount.html">759</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Pivot-mount_base.html">855</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Pivot-mount.html">903</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/PrimaryButton-mount_base.html">857</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/PrimaryButton-mount.html">859</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Rating-mount_base.html">4646</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Rating-mount.html">4712</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/SearchBox-mount_base.html">919</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/SearchBox-mount.html">913</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Shimmer-mount_base.html">1879</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Shimmer-mount.html">1905</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Slider-mount_base.html">1347</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Slider-mount.html">1363</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/SpinButton-mount_base.html">2899</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/SpinButton-mount.html">2951</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Spinner-mount_base.html">382</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Spinner-mount.html">385</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/SplitButton-mount_base.html">1834</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/SplitButton-mount.html">1808</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Stack-mount_base.html">420</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Stack-mount.html">405</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/StackWithIntrinsicChildren-mount_base.html">866</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/StackWithIntrinsicChildren-mount.html">871</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/StackWithTextChildren-mount_base.html">2651</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/StackWithTextChildren-mount.html">2639</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/SwatchColorPicker-mount_base.html">6119</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/SwatchColorPicker-mount.html">6150</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/TagPicker-mount_base.html">1483</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/TagPicker-mount.html">1494</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Text-mount_base.html">368</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Text-mount.html">376</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/TextField-mount_base.html">933</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/TextField-mount.html">916</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/ThemeProvider-mount_base.html">838</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/ThemeProvider-mount.html">838</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/ThemeProvider-virtual-rerender_base.html">597</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/ThemeProvider-virtual-rerender.html">589</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1304</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1319</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Toggle-mount_base.html">600</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/Toggle-mount.html">602</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/buttonNative-mount_base.html">192</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30296/perf-test/buttonNative-mount.html">191</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>
