### ISSUE TITLE
[GroupedList] Not re-rendering on groups / compact prop change

### ISSUE THREAD

**Issue by known-as-bmf** [microsoft/fluentui#15272]
### Environment Information

- **Package version(s)**: `7.142.0`
- **Browser and OS versions**: Not relevant

### Issue

In `GroupedList.base.tsx`, when the props change, there is a check to figure out if it is worth re-rendering the list : https://github.com/microsoft/fluentui/blame/7fc8435387fa90c21cdc396b41ed43f6f9e7979b/packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.base.tsx#L44

Unfortunately, I think it is broken since the check compares difference between the same references. See below:

https://github.com/microsoft/fluentui/blame/7fc8435387fa90c21cdc396b41ed43f6f9e7979b/packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.base.tsx#L50

https://github.com/microsoft/fluentui/blame/7fc8435387fa90c21cdc396b41ed43f6f9e7979b/packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.base.tsx#L65

https://github.com/microsoft/fluentui/blame/7fc8435387fa90c21cdc396b41ed43f6f9e7979b/packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.base.tsx#L72

The `if`s line 61 and 68 will **always** return false since we are comparing the same references (see object destructuring line 50).

### Please provide a reproduction of the bug in a codepen:

I think the problem is visible here on the first example https://developer.microsoft.com/en-us/fluentui#/controls/web/groupedlist

Try toggling compact mode, nothing happens.

#### Actual behavior:

`GroupedList` not re-rendering with new `groups` / `compact` props.

#### Expected behavior:

`GroupedList` re-rendering with new `groups` / `compact` props.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: N/A

EDIT: updated the line numbers

**Comment by paulgildea** [comment]
@known-as-bmf Thanks for the issue.

@dzearing FYI

**Comment by dzearing** [comment]
This seems to have been caused by https://github.com/microsoft/fluentui/pull/15228.

**Comment by dzearing** [comment]
@ThomasMichon - what do you think?

**Comment by dzearing** [comment]
This should be resolved in https://github.com/microsoft/fluentui/pull/15284

**Comment by known-as-bmf** [comment]
Not for groups

https://github.com/ThomasMichon/office-ui-fabric-react/blob/be83c761af8af1fcf230c66db3ccbf23b3892b0e/packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.base.tsx#L50
https://github.com/ThomasMichon/office-ui-fabric-react/blob/be83c761af8af1fcf230c66db3ccbf23b3892b0e/packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.base.tsx#L65

```ts
    const { groups, selectionMode, compact } = nextProps;
    //...
    if (nextProps.groups !== groups) {
      nextState = {
        ...nextState,
        groups: nextProps.groups,
      };
    }
```

**Comment by ThomasMichon** [comment]
If there are new groups for the `GroupedList` to render, or the fields of a single group have changed, the caller should be supplying a whole new `groups` array to the `GroupedList` props.

Also, keep in mind that `getDerivedStateFromProps` is *not* responsible for determining whether a component should render; it's just making sure the internal state reflects that of the current props, for which a simple identity test is sufficient. Since `GroupedList` does not implement `shouldComponentUpdate`, it's up to the caller to supply a new actual prop value to make the component re-render.

**Comment by known-as-bmf** [comment]
>  getDerivedStateFromProps is not responsible for determining whether a component should render

Yeah sorry, it was an oversimplification.

The code is still incorrect.

> If there are new groups for the GroupedList to render, or the fields of a single group have changed, the caller should be supplying a whole new groups array to the GroupedList props.

This is what i'm doing and it doesn't work.

Look a this code:

```ts
    const { groups, selectionMode, compact } = nextProps;
    //...
    if (nextProps.groups !== groups) {
      nextState = {
        ...nextState,
        groups: nextProps.groups,
      };
    }
```

The property `groups` in the state is **NEVER** updated. It is **impossible** to enter the `if`.

Codepen for repro:
https://codepen.io/known-as-bmf/pen/BaKerJL
(items & groups are `[]` until you click on the button, then, they are assigned correct values and nothing updates)

**Comment by miroslavstastny** [comment]
@ThomasMichon - I think there is a bug in `getDerivedStateFromProps`:
https://github.com/microsoft/fluentui/blob/7fc8435387fa90c21cdc396b41ed43f6f9e7979b/packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.base.tsx#L50-L70

On line 50, `groups` is decomposed from `nextProps` to be compares with `nextProps.groups` on line 65.
65 should compare `nextProps.groups !== previousState.groups`.

**Comment by miroslavstastny** [comment]
The same issue with `selectionMode` and `compact`. @ThomasMichon could you please check?

**Comment by dzearing** [comment]
I believe this should be addressed here: https://github.com/microsoft/fluentui/pull/15321
