### ISSUE TITLE
TypeError from Jest: element.getBoundingClientRect is not a function. After upgrade @fluentui/react to v8.113.1.

### ISSUE THREAD

**Issue by nishila2** [microsoft/fluentui#30134]
### Environment Information

NodeJS: 18.19.0
npm: 10.2.3
typescript: 4.9.5
@fluentui/react: 8.113.1
jest: 28.1.3
jest-environment-jsdom: 28.1.3
@testing-library/jest-dom: 5.17.0
@testing-library/react: 12.1.5
@testing-library/react-hooks: 8.0.1
@testing-library/user-event: 13.5.0

After the upgrade of @fluentui/react to v8.113.1, Jest started to complain, `TypeError: element.getBoundingClientRect is not a functionJest`.

psuedo code:
Get a row from the list and open the context menu (callout).
`
const rows = within(aList).getAllByRole("row");
const row = rows[1];
fireEvent.contextMenu(row);
`
This code should open a context menu. But instead, this line `fireEvent.contextMenu(row);` complains, `TypeError: element.getBoundingClientRect is not a functionJest`.

FYI: https://github.com/microsoft/fluentui/blob/master/packages/react/CHANGELOG.md#minor-changes

**Comment by nanivijay** [comment]
I am facing the same issue after upgrading fluent ui to 8.117.5. Did you find a solution for this issue?

**Comment by noxumnishil** [comment]
@nanivijay Now I am using version 8.118.3

**Comment by nanivijay** [comment]
Thanks for the reply @noxumnishil . I upgraded the lib to 8.118.3. I still the same issue. I will investigate more
