### PR TITLE
Fix positioning visibility with unavailable layout

### PR DESCRIPTION
**Pull request by bsunderhus**
## Problem

After upgrading `@fluentui/react-tooltip` from 9.10.3 to 9.10.5, TMP jsdom tests render visible Tooltips with `visibility: hidden`. The behavior was introduced by #36386 (shipped in 9.10.4), which hides a Tooltip whenever positioning reports either `escaped` or `referenceHidden`.

## Investigation and Root Cause

#36432 added those visibility flags to the positioning-end event, and #36386 consumes them in Tooltip. In a browser, that is correct when a trigger scrolls outside an overflow container.

The same computation is not meaningful in jsdom: it does not implement layout, so the reference element, floating element, and document root report zero geometry. Floating UI therefore reports:

```ts
{ escaped: true, referenceHidden: true }
```

Tooltip interprets those flags as confirmed clipping and applies `visibility: hidden`, even though no clipping was measured. Existing Jest coverage only dispatched synthetic visibility events, so it did not exercise this path.

## Solution

Treat positioning visibility as indeterminate only when the document has no layout viewport (`document.documentElement.clientWidth === 0` and `clientHeight === 0`). In that case, normalize `escaped` and `referenceHidden` to `false` before positioning attributes are written and `onPositioningEnd` is dispatched.

This deliberately does not use the trigger or floating element rectangles as the signal: zero-sized or clipped elements can be legitimate browser states. When a browser layout viewport exists, the existing Floating UI behavior remains unchanged, including hiding and restoring Tooltips as a trigger scrolls out of and back into an overflow container.

## Coverage

- Adds positioning-manager coverage for both unavailable and measurable viewports, including positioning visibility attributes.
- Adds a Tooltip jsdom integration regression that waits for the real positioning callback and confirms the Tooltip remains visible.
- Updates two GanttChart snapshots that captured jsdom’s former false `data-popper-escaped` and `data-popper-reference-hidden` attributes.
- Retains the existing browser Cypress coverage for overflow scrolling behavior.

## Validation

- `yarn nx run react-positioning:test --runInBand`
- `yarn nx run react-tooltip:test --runInBand --testPathPatterns=Tooltip.test.tsx`
- `yarn nx run react-charts:test --runInBand --testPathPatterns=GanttChart.test.tsx -u`

Related to #36386 and #36432.

### CODE REVIEW

**Review by PaulGMardling — APPROVED** [review]
Looks good to me. 
Normalizing the visibility flags before both attribute updates and event dispatch keeps them consistent, while preserving clipping behavior when a layout viewport is available.

**Review by tomas-vodrazka — APPROVED** [review]
lgtm

**Review by AtishayMsft — APPROVED** [review]
